; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103CB]
platform = ststm32
board = genericSTM32F103C8
;board = genericSTM32F103CB
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
board_upload.maximum_size = 131072
upload_flags = -c set FLASH_SIZE 0x20000  
build_flags = 
    -std=gnu++11
    -Os
    -flto
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -DSTACK_SIZE=4096
    -D ENABLE_HWSERIAL1
    -Wl,--print-memory-usage
    -Wl,--gc-sections

    ; RadioLib optimize
    -DRADIOLIB_EXCLUDE_CC1101
    -DRADIOLIB_EXCLUDE_NRF24
    -DRADIOLIB_EXCLUDE_SX128X
    -DRADIOLIB_EXCLUDE_RFM69
    -DRADIOLIB_EXCLUDE_AX25
    -DRADIOLIB_EXCLUDE_BELL
    -DRADIOLIB_EXCLUDE_MORSE
    -DRADIOLIB_EXCLUDE_APRS
lib_deps =
    jgromes/RadioLib
    ;olikraus/U8g2
    arduino-libraries/SD @ ^1.2.4
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/Adafruit SHTC3 Library
    khoih-prog/FlashStorage_STM32

monitor_filters = direct